repos:
  - repo: https://github.com/psf/black
    rev: 23.9.1  # Use a versão mais recente disponível
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0  # Use a versão mais recente disponível
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5  # Use a versão mais recente disponível
    hooks:
      - id: bandit
        args: ["-r"]  # Recursivo, para analisar todo o repositório

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use a versão mais recente disponível
    hooks:
      - id: check-yaml
        exclude: ^\.github/
      - id: end-of-file-fixer
      - id: trailing-whitespace
