repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use a versão mais recente disponível
    hooks:
      - id: black

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.1  # Use a versão mais recente disponível
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.3  # Use a versão mais recente disponível
    hooks:
      - id: bandit
        args: ["-r"]  # Recursivo, para analisar todo o repositório

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use a versão mais recente disponível
    hooks:
      - id: check-yaml
        exclude: ^\.github/
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.97.4  # Use a versão mais recente disponível
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_tflint
      - id: terraform_trivy
        args:
          - --args="--severity=CRITICAL,HIGH"
