name: Deploy

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  LAMBDA_FUNCTION_NAME: potiguana-ufrn-bot
  LAMBDA_ARN: arn:aws:lambda:us-east-1:461018071700:function:potiguana-ufrn-bot
  LAYER_NAME: potiguana-requirements-layer
  LAYER_DESCRIPTION: "Python libraries for my Potiguana bot"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Package Lambda Code
      working-directory: ./src
      run: |
        zip -r ../deployment-package.zip .  # Compacta apenas o conteúdo de `src`

    - name: Deploy Lambda Function
      working-directory: ./src
      run: |
        aws lambda put-function-concurrency --function-name ${{ env.LAMBDA_FUNCTION_NAME }} --reserved-concurrent-executions 0
        aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://../deployment-package.zip > /dev/null
        aws lambda update-function-configuration \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --layers arn:aws:lambda:us-east-1:461018071700:layer:potiguana-requirements-layer:10
          --timeout 60 > /dev/null
        aws lambda delete-function-concurrency --function-name ${{ env.LAMBDA_FUNCTION_NAME }}
